-- CreateEnum
CREATE TYPE "Action" AS ENUM ('VIEW_REGISTRATION_DETAILS', 'VIEW_ALL_COMPETITIONS', 'EDIT_COMPETITION_TIME', 'VIEW_STALL_DETAILS', 'ADD_NEW_STALL', 'EDIT_STALL', 'DELETE_STALL', 'VIEW_ALL_COMPANIES', 'ADD_NEW_COMPANY', 'ASSIGN_BOOTH', 'EDIT_COMPANY', 'DELETE_COMPANY', 'CREATE_NEW_REGISTRATION', 'UPDATE_ATTENDANCE', 'VIEW_ALL_PORTAL_USERS', 'ASSIGN_ACTIONS_TO_USERS', 'CREATE_ACCOUNTS', 'UPDATE_PARTICIPANT_RECORD');

-- CreateTable
CREATE TABLE "UserAction" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "action" "Action" NOT NULL,
    "grantedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "grantedBy" TEXT,

    CONSTRAINT "UserAction_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "UserAction_userId_idx" ON "UserAction"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "UserAction_userId_action_key" ON "UserAction"("userId", "action");

-- AddForeignKey
ALTER TABLE "UserAction" ADD CONSTRAINT "UserAction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserAction" ADD CONSTRAINT "UserAction_grantedBy_fkey" FOREIGN KEY ("grantedBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
